-- Run with psql -v legacy_phone='+8613800000000' -v legacy_password_hash='...'.
-- The password hash must be generated by the future registration code (Argon2id or bcrypt).
-- Back up the database and stop all API/worker processes before running this migration.
\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone varchar(20) NOT NULL,
    password_hash varchar(255) NOT NULL,
    phone_verified_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_key ON users (phone);

-- Existing rows are assigned to one explicitly supplied account. Re-running keeps its password.
INSERT INTO users (phone, password_hash, phone_verified_at, created_at, updated_at)
VALUES (:'legacy_phone', :'legacy_password_hash', now(), now(), now())
ON CONFLICT (phone) DO NOTHING;

SELECT set_config('narra.legacy_owner_id',
    (SELECT id::text FROM users WHERE phone = :'legacy_phone'), true);

DO $$
DECLARE
    table_name text;
    owner_id bigint := current_setting('narra.legacy_owner_id')::bigint;
    tables text[] := ARRAY[
        'folders', 'classrooms', 'knowledge_documents', 'knowledge_upload_records',
        'preset_agents', 'llm_providers', 'embedding_settings', 'embedding_models',
        'rerank_settings', 'vlm_settings', 'mcp_servers'
    ];
BEGIN
    FOREACH table_name IN ARRAY tables LOOP
        IF to_regclass(format('%I', table_name)) IS NULL THEN
            CONTINUE;
        END IF;
        EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS owner_id bigint', table_name);
        EXECUTE format('UPDATE %I SET owner_id = $1 WHERE owner_id IS NULL', table_name) USING owner_id;
        EXECUTE format('ALTER TABLE %I ALTER COLUMN owner_id SET NOT NULL', table_name);
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = table_name || '_owner_id_fkey') THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT',
                table_name, table_name || '_owner_id_fkey');
        END IF;
        EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (owner_id)',
            'idx_' || table_name || '_owner_id', table_name);
    END LOOP;
END $$;

-- Drop only the old single-column uniqueness rules. Composite uniqueness is created below.
DO $$
DECLARE
    item record;
    target record;
BEGIN
    FOR target IN SELECT * FROM (VALUES
        ('preset_agents', 'agent_key'), ('preset_agents', 'sort_order'),
        ('llm_providers', 'name'), ('embedding_settings', 'name'),
        ('embedding_models', 'name'), ('rerank_settings', 'name'),
        ('vlm_settings', 'name'), ('mcp_servers', 'server_id')
    ) AS x(table_name, column_name) LOOP
        IF to_regclass(format('%I', target.table_name)) IS NULL THEN
            CONTINUE;
        END IF;
        FOR item IN
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = c.conkey[1]
            WHERE c.conrelid = target.table_name::regclass AND c.contype = 'u'
              AND array_length(c.conkey, 1) = 1 AND a.attname = target.column_name
        LOOP
            EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', target.table_name, item.conname);
        END LOOP;
        FOR item IN
            SELECT ic.relname AS index_name
            FROM pg_index ix
            JOIN pg_class ic ON ic.oid = ix.indexrelid
            JOIN pg_attribute a ON a.attrelid = ix.indrelid AND a.attnum = ix.indkey[0]
            WHERE ix.indrelid = target.table_name::regclass AND ix.indisunique
              AND ix.indnkeyatts = 1 AND a.attname = target.column_name
              AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = ix.indexrelid)
        LOOP
            EXECUTE format('DROP INDEX %I', item.index_name);
        END LOOP;
    END LOOP;
END $$;

-- Replace global partial unique indexes; the predicate remains the same, keyed by owner.
DROP INDEX IF EXISTS embedding_settings_one_active_idx;
DROP INDEX IF EXISTS embedding_models_one_default_idx;
DROP INDEX IF EXISTS rerank_settings_one_enabled_idx;
DROP INDEX IF EXISTS vlm_settings_one_enabled_idx;

DO $$
DECLARE
    index_def text;
    target_table text;
BEGIN
    FOR target_table, index_def IN SELECT * FROM (VALUES
        ('preset_agents', 'CREATE UNIQUE INDEX IF NOT EXISTS preset_agents_owner_agent_key_key ON preset_agents (owner_id, agent_key)'),
        ('preset_agents', 'CREATE UNIQUE INDEX IF NOT EXISTS preset_agents_owner_sort_order_key ON preset_agents (owner_id, sort_order)'),
        ('llm_providers', 'CREATE UNIQUE INDEX IF NOT EXISTS llm_providers_owner_name_key ON llm_providers (owner_id, name)'),
        ('embedding_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS embedding_settings_owner_name_key ON embedding_settings (owner_id, name)'),
        ('embedding_models', 'CREATE UNIQUE INDEX IF NOT EXISTS embedding_models_owner_name_key ON embedding_models (owner_id, name)'),
        ('rerank_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS rerank_settings_owner_name_key ON rerank_settings (owner_id, name)'),
        ('vlm_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS vlm_settings_owner_name_key ON vlm_settings (owner_id, name)'),
        ('mcp_servers', 'CREATE UNIQUE INDEX IF NOT EXISTS mcp_servers_owner_server_id_key ON mcp_servers (owner_id, server_id)'),
        ('embedding_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS embedding_settings_one_active_idx ON embedding_settings (owner_id) WHERE is_active'),
        ('embedding_models', 'CREATE UNIQUE INDEX IF NOT EXISTS embedding_models_one_default_idx ON embedding_models (owner_id) WHERE is_default'),
        ('rerank_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS rerank_settings_one_enabled_idx ON rerank_settings (owner_id) WHERE is_enabled'),
        ('vlm_settings', 'CREATE UNIQUE INDEX IF NOT EXISTS vlm_settings_one_enabled_idx ON vlm_settings (owner_id) WHERE is_enabled')
    ) AS x(table_name, definition) LOOP
        IF to_regclass(format('%I', target_table)) IS NOT NULL THEN
            EXECUTE index_def;
        END IF;
    END LOOP;
END $$;

COMMIT;
